### ISSUE TITLE
IPF-22

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#24] opened 2022-04-19 12:07 UTC
Adapting triangulation algorithm to C# from Python.

- [x] Rewrite algorithm in Python - 2 Days
- [x] Write out the algorithm in C# - 2 Days

**Comment by JoshuaOC97** [comment] 2022-04-22 12:29
Triangulation algorithm completed in Python but has some design flaws (hopefully can be fixed during translation). Started the translation to C#.

**Comment by Josh-Danks** [comment] 2022-04-26 12:44
-Blocker of learning Unity
-Task added to rewrite Python
-Translation into C# reduced to a day

**Comment by Josh-Danks** [comment] 2022-05-03 12:39
-Python algorithm almost complete 
-Blocker => checking maths is correct
-Reed assigned to start translating into C#

**Comment by JoshuaOC97** [comment] 2022-05-06 16:07
Added code to the scripts folder, awaiting acceptance for the addition.

**Comment by Josh-Danks** [comment] 2022-05-10 11:57
-Oliver-Cole's stuff done
-Reed to do translation
-Reduced translation to 2 days

**Comment by jopokemine** [comment] 2022-05-28 14:29
This is essentially a partial duplicate of #15, and since there is already a test task there, and the implemenation tasks for this issue have been achieved, I have removed the test task here (#15 test task will cover this) and am closing this issue.

**Closed by jopokemine** 2022-05-28 14:29 UTC
Labels: MVP, Must, Tracking
