### ISSUE TITLE
IPF-18

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#18] opened 2022-03-21 22:57 UTC
The application will find the user's location in relation to a defined grid

_**Dependency IPF-15**_

- [x] Application will triangulate the user's position based on the bluetooth strengths obtained (IPF15)
- [x] Position will be translated into grid coordinates

**Comment by jopokemine** [comment] 2022-05-28 14:27
This is essentially a partial duplicate of #15, and since the implementation is done for this issue, and there is a test task in #15, I am closing this issue

**Closed by jopokemine** 2022-05-28 14:27 UTC
Labels: MVP, Must, Tracking
